# Generated by Django 2.2.14 on 2020-07-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Marca',
        ),
    ]
