# Generated by Django 2.2.14 on 2020-07-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='id_categoria',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='id_marca',
            field=models.IntegerField(null=True),
        ),
    ]
